#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
polybar tokyo-night &
nitrogen --restore &
picom &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
alsactl init &
betterlockscreen -u ~/Pictures/Wallpapers/snowcaped.png &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V


bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^5'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


